name = "tiendatecnonauta"
compatibility_date = "2024-09-01"
main = "src/index.js"

[assets]
directory = "public"
binding = "ASSETS"

# Base de datos D1 - reemplazá "database_name" y "database_id" por los reales
# de la base que ya creaste en Cloudflare (D1 SQLite Database).
[[d1_databases]]
binding = "DB"
database_name = "tiendatecnonauta"
database_id = "2cc73d47-3758-48ba-ae3b-bd35ad1b35c5"
